import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs' 


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hayden Walker Portfolio</title>
        <meta name="description" content="Generated by create next app + tailwindCSS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-burtons'>designedbyhwalk1</h1>
            <ul className='flex items-center '>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl mr-6'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div>
            <h2>Hayden Walker</h2>
            <h3>Developer</h3>
            <p>
              Software Developer working in Melbourne, Australia.
              A curious learner and team player searching for a challenging position as a Graduate Software Developer with Arq Group to 
              utilise my technical competencies, working knowledge of software development, problem solving and collaboration skills to 
              grow as a developer.
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}
